export const exploreFeaturedContent = {
  eyebrow: "Featured Products",
  title: "Handpicked from Varanasi",
  description: "Authentic, high-quality products crafted by local artisans.",
};

export const exploreFeaturedFilters = [
  { id: "all", label: "All" },
  { id: "sarees", label: "Sarees" },
  { id: "handicrafts", label: "Handicrafts" },
  { id: "spiritual", label: "Spiritual" },
  { id: "souvenirs", label: "Souvenirs" },
];

// Images online placeholder hain - baad me har product ki apni image se replace kar lena
const PLACEHOLDER =
  "https://images.unsplash.com/photo-1561359313-0639aad49ca6?auto=format&fit=crop&w=600&q=75";

// Pehle 5 products screenshot ke hain, baaki dummy hain taaki slider aur filters sahi chalein
export const exploreFeaturedProducts = [
  {
    id: 1,
    category: "sarees",
    name: "Banarasi Katan Silk Saree",
    rating: 4.8,
    reviews: 124,
    price: 12999,
    oldPrice: 15999,
    image: PLACEHOLDER,
    fallback: "from-[#a8324a] to-[#2a0f18]",
  },
  {
    id: 2,
    category: "sarees",
    name: "Banarasi Georgette Saree",
    rating: 4.6,
    reviews: 59,
    price: 8999,
    oldPrice: 11999,
    image: PLACEHOLDER,
    fallback: "from-[#c0306a] to-[#3a0f22]",
  },
  {
    id: 3,
    category: "spiritual",
    name: "Brass Kashi Vishwanath Idol",
    rating: 4.9,
    reviews: 215,
    price: 2499,
    oldPrice: 3499,
    image: PLACEHOLDER,
    fallback: "from-[#b5802a] to-[#3a2a10]",
  },
  {
    id: 4,
    category: "spiritual",
    name: "Rudraksha Mala",
    rating: 4.7,
    reviews: 168,
    price: 599,
    oldPrice: 999,
    image: PLACEHOLDER,
    fallback: "from-[#8a4a2a] to-[#2a140c]",
  },
  {
    id: 5,
    category: "sarees",
    name: "Banarasi Handloom Dupatta",
    rating: 4.8,
    reviews: 87,
    price: 3999,
    oldPrice: 5499,
    image: PLACEHOLDER,
    fallback: "from-[#2a4a9a] to-[#0f1a3a]",
  },
  {
    id: 6,
    category: "handicrafts",
    name: "Wooden Lacquerware Box",
    rating: 4.5,
    reviews: 42,
    price: 1299,
    oldPrice: 1799,
    image: PLACEHOLDER,
    fallback: "from-[#c0502a] to-[#3a140c]",
  },
  {
    id: 7,
    category: "spiritual",
    name: "Handcrafted Brass Diya Set",
    rating: 4.7,
    reviews: 96,
    price: 449,
    oldPrice: 599,
    image: PLACEHOLDER,
    fallback: "from-[#c98a3a] to-[#4a2a10]",
  },
  {
    id: 8,
    category: "souvenirs",
    name: "Varanasi Ghats Magnet Set",
    rating: 4.4,
    reviews: 38,
    price: 299,
    oldPrice: 399,
    image: PLACEHOLDER,
    fallback: "from-[#e08a5a] to-[#3a2a3a]",
  },
  {
    id: 9,
    category: "handicrafts",
    name: "Wooden Toy Set (Kashi Craft)",
    rating: 4.6,
    reviews: 51,
    price: 799,
    oldPrice: 999,
    image: PLACEHOLDER,
    fallback: "from-[#b5702a] to-[#3a1e0c]",
  },
  {
    id: 10,
    category: "sarees",
    name: "Banarasi Brocade Stole",
    rating: 4.7,
    reviews: 73,
    price: 2299,
    oldPrice: 2999,
    image: PLACEHOLDER,
    fallback: "from-[#6a2a8a] to-[#1f0f2a]",
  },
  {
    id: 11,
    category: "souvenirs",
    name: "Copper Ganga Jal Kalash",
    rating: 4.6,
    reviews: 64,
    price: 699,
    oldPrice: 899,
    image: PLACEHOLDER,
    fallback: "from-[#d98a6a] to-[#2a2a3a]",
  },
];
