export const exploreBestSellersContent = {
  eyebrow: "Best Sellers",
  title: "Loved by Our Customers",
  buttonText: "View All Products",
  buttonPath: "/shop",
};

// Images online placeholder hain - baad me har product ki apni image se replace kar lena
const PLACEHOLDER =
  "https://images.unsplash.com/photo-1561359313-0639aad49ca6?auto=format&fit=crop&w=600&q=75";

// Pehle 5 products screenshot ke hain, baaki 3 dummy hain taaki infinite loop sahi chale
export const exploreBestSellers = [
  {
    id: 1,
    slug: "banarasi-silk-stole",
    name: "Banarasi Silk Stole",
    rating: 4.8,
    reviews: 112,
    price: 1999,
    oldPrice: 2999,
    image: PLACEHOLDER,
    fallback: "from-[#8a2a8a] to-[#2a0f2a]",
  },
  {
    id: 2,
    slug: "wooden-elephant-figurine",
    name: "Wooden Elephant Figurine",
    rating: 4.7,
    reviews: 98,
    price: 899,
    oldPrice: 1399,
    image: PLACEHOLDER,
    fallback: "from-[#b5702a] to-[#3a1e0c]",
  },
  {
    id: 3,
    slug: "kashi-temple-wall-art",
    name: "Kashi Temple Wall Art",
    rating: 4.9,
    reviews: 76,
    price: 1499,
    oldPrice: 2199,
    image: PLACEHOLDER,
    fallback: "from-[#8a6a3a] to-[#2a1f10]",
  },
  {
    id: 4,
    slug: "handcrafted-pooja-thali",
    name: "Handcrafted Pooja Thali",
    rating: 4.9,
    reviews: 152,
    price: 1299,
    oldPrice: 1999,
    image: PLACEHOLDER,
    fallback: "from-[#c98a3a] to-[#4a2a10]",
  },
  {
    id: 5,
    slug: "banarasi-saree-gift-box",
    name: "Banarasi Saree Gift Box",
    rating: 4.7,
    reviews: 64,
    price: 599,
    oldPrice: 899,
    image: PLACEHOLDER,
    fallback: "from-[#a8324a] to-[#2a0f18]",
  },
  {
    id: 6,
    slug: "brass-ganesha-idol",
    name: "Brass Ganesha Idol",
    rating: 4.8,
    reviews: 88,
    price: 1099,
    oldPrice: 1499,
    image: PLACEHOLDER,
    fallback: "from-[#b5802a] to-[#3a2a10]",
  },
  {
    id: 7,
    slug: "handwoven-silk-dupatta",
    name: "Handwoven Silk Dupatta",
    rating: 4.6,
    reviews: 54,
    price: 1799,
    oldPrice: 2499,
    image: PLACEHOLDER,
    fallback: "from-[#2a4a9a] to-[#0f1a3a]",
  },
  {
    id: 8,
    slug: "lacquer-bangle-set",
    name: "Lacquer Bangle Set",
    rating: 4.5,
    reviews: 33,
    price: 399,
    oldPrice: 599,
    image: PLACEHOLDER,
    fallback: "from-[#c0502a] to-[#3a140c]",
  },
];
